# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lab 5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab 5
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FirebaseFirestoreSwift'

end
